import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AntDesignTheme from "@/theme";
import LayoutProvider from "@/layout-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Supa Finance App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntDesignTheme>
          <LayoutProvider>{children}</LayoutProvider>
        </AntDesignTheme>
      </body>
    </html>
  );
}
